var thirukkural133E = {"Chapter1":"The Praise of God",
"Chapter2":"The Blessing of Rain",
"Chapter3":"The Merit of Ascetics",
"Chapter4":"The Power of Virtue",
"Chapter5":"Married Life",
"Chapter6":"The Worth of a Wife",
"Chapter7":"The Wealth of Children",
"Chapter8":"Loving-Kindness",
"Chapter9":"Hospitality",
"Chapter10":"Sweet Words",
"Chapter11":"Gratitude",
"Chapter12":"Equity",
"Chapter13":"Self Control",
"Chapter14":"Good Decorum",
"Chapter15":"Against Coveting Another’s Wife",
"Chapter16":"Forgiveness",
"Chapter17":"Avoid Envy",
"Chapter18":"Against Covetousness",
"Chapter19":"Against Slander",
"Chapter20":"Against Vain Speaking",
"Chapter21":"Fear of Sin",
"Chapter22":"Duty to Society",
"Chapter23":"Charity",
"Chapter24":"Renown",
"Chapter25":"Compassion",
"Chapter26":"Abstinence from Flesh",
"Chapter27":"Penance",
"Chapter28":"Imposture",
"Chapter29":"The Absence of Fraud",
"Chapter30":"Veracity",
"Chapter31":"Restraining Anger",
"Chapter32":"Non Violence",
"Chapter33":"Non Killing",
"Chapter34":"Instability",
"Chapter35":"Renunciation",
"Chapter36":"Truth-Conciousness",
"Chapter37":"Curbing of Desire",
"Chapter38":"Destiny",
"Chapter39":"The Grandeur of Monarchy",
"Chapter40":"Education",
"Chapter41":"Non Learning",
"Chapter42":"Listening",
"Chapter43":"Possession of Wisdom",
"Chapter44":"Avoid Faults",
"Chapter45":"Gaining Great Men’s Help",
"Chapter46":"Avoiding Mean Company",
"Chapter47":"Deliberation before Action",
"Chapter48":"Judging Strength",
"Chapter49":"Knowing Proper Time",
"Chapter50":"Judging The Place",
"Chapter51":"Testing of Men for Confidence",
"Chapter52":"Testing and Entrusting",
"Chapter53":"Cherishing Kinsmen",
"Chapter54":"Unforgetfulness",
"Chapter55":"Just Government",
"Chapter56":"Cruel Tyranny",
"Chapter57":"Avoiding Terrorism",
"Chapter58":"Benign Looks",
"Chapter59":"Espionage",
"Chapter60":"Energy",
"Chapter61":"Freedom from Sloth",
"Chapter62":"Manly Effort",
"Chapter63":"Hope in Mishap",
"Chapter64":"Ministers",
"Chapter65":"Power of Speech",
"Chapter66":"Purity of Action",
"Chapter67":"Powerful Acts",
"Chapter68":"Modes of Action",
"Chapter69":"Embassy",
"Chapter70":"Walk with Kings",
"Chapter71":"Divining the Mind",
"Chapter72":"Judging the Audience",
"Chapter73":"Courage before Councils",
"Chapter74":"The Country",
"Chapter75":"Fortress",
"Chapter76":"Ways of Making Wealth",
"Chapter77":"The Glory of Army",
"Chapter78":"Military Pride",
"Chapter79":"Friendship",
"Chapter80":"Testing Friendship",
"Chapter81":"Intimacy",
"Chapter82":"Bad Friendship",
"Chapter83":"False Friendship",
"Chapter84":"Folly",
"Chapter85":"Petty Conceit",
"Chapter86":"Hatred",
"Chapter87":"Noble Hostility",
"Chapter88":"Appraising Enemies",
"Chapter89":"Secret Foe",
"Chapter90":"Offend not the Great",
"Chapter91":"Being led by Women",
"Chapter92":"Wanton Women",
"Chapter93":"Not Drinking Liquor",
"Chapter94":"Gambling",
"Chapter95":"Medicine",
"Chapter96":"Nobility",
"Chapter97":"Honour",
"Chapter98":"Greatness",
"Chapter99":"Sublimity",
"Chapter100":"Courtesy",
"Chapter101":"Futile Wealth",
"Chapter102":"Sensitiveness to Shame",
"Chapter103":"Promoting Family Welfare",
"Chapter104":"Farming",
"Chapter105":"Poverty",
"Chapter106":"Asking",
"Chapter107":"Dread of Beggary",
"Chapter108":"Meanness",
"Chapter109":"Beauty’s Dart",
"Chapter110":"Signs Speak the Heart",
"Chapter111":"Embrace-Bliss",
"Chapter112":"Beauty Extolled",
"Chapter113":"Love’s Excellence",
"Chapter114":"Decorum Defied",
"Chapter115":"Public Clamour",
"Chapter116":"Pangs of Separation",
"Chapter117":"Wailing of Pining Love",
"Chapter118":"Wasteful Look for Wistful Love",
"Chapter119":"Wailing over Pallor",
"Chapter120":"Pining Alone",
"Chapter121":"Sad Memories",
"Chapter122":"Dream Visions",
"Chapter123":"Eventide Sigh",
"Chapter124":"Limbs Languish",
"Chapter125":"Soliloquy",
"Chapter126":"Reserve Lost!",
"Chapter127":"Mutual Yearning",
"Chapter128":"Feeling Surmised",
"Chapter129":"Longing for Reunion",
"Chapter130":"Chiding the Heart",
"Chapter131":"Bouderie",
"Chapter132":"Feigned Anger",
"Chapter133":"Sulking Charm"};

